### ISSUE TITLE
Raise an Exception if json_column_name specified no exists column. 

### ISSUE THREAD

**Issue by hiroyuki-sato** [smdmts/embulk-filter-json_key_joiner#2]
The following configuration has invalid `json_column_name` name `record // JSON Type Column`.
This is because the `//` character isn't commenting mark. 
But embulk run finished without append column. 

I would like to catch an exception if `json_column_name` specified no exists column. 

```yaml
in:
  type: file
  path_prefix: test.json
  parser:
    type: json

filters:
  - type: json_key_joiner
    json_column_name: record // JSON Type Column
    key_value:
      added: fuga

out:
  type: stdout
```
